import { Encrypter } from "age-encryption";
import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";

import { decryptWithPassphrase, encryptWithPassphrase } from "../src/crypto";

const PASSWORD = "correct horse battery staple";

describe("decryptWithPassphrase", () => {
  it("round-trips edited Unicode Markdown with the plugin encryptor", async () => {
    const markdown = "# 编辑后的标题\n\n正文、emoji 🔐 and `code`.\n";
    const ciphertext = await encryptWithPassphrase(markdown, PASSWORD);
    const plaintext = await decryptWithPassphrase(ciphertext, PASSWORD);

    expect(new TextDecoder().decode(plaintext)).toBe(markdown);
  });

  it("uses fresh randomness when saving the same Markdown twice", async () => {
    const first = await encryptWithPassphrase("same plaintext", PASSWORD);
    const second = await encryptWithPassphrase("same plaintext", PASSWORD);

    expect(first).not.toEqual(second);
    await expect(decryptWithPassphrase(first, "wrong password")).rejects.toThrow();
  });

  it("decrypts passphrase-encrypted age data including Unicode", async () => {
    const encrypter = new Encrypter();
    encrypter.setScryptWorkFactor(14);
    encrypter.setPassphrase(PASSWORD);
    const ciphertext = await encrypter.encrypt("# 你好\n\nObsidian ✨\n");

    const plaintext = await decryptWithPassphrase(ciphertext, PASSWORD);
    expect(new TextDecoder().decode(plaintext)).toBe("# 你好\n\nObsidian ✨\n");
  });

  it("rejects a wrong password", async () => {
    const encrypter = new Encrypter();
    encrypter.setScryptWorkFactor(14);
    encrypter.setPassphrase(PASSWORD);
    const ciphertext = await encrypter.encrypt("secret");

    await expect(decryptWithPassphrase(ciphertext, "wrong password")).rejects.toThrow();
  });

  it("decrypts a fixture generated by the Go age library", async () => {
    const ciphertext = await readFile(
      new URL("./fixtures/go-generated.md.age", import.meta.url)
    );
    const plaintext = await decryptWithPassphrase(ciphertext, PASSWORD);

    expect(new TextDecoder().decode(plaintext)).toBe(
      "# Go compatibility\n\n你好 from filippo.io/age ✨\n"
    );
  });
});
